FROM node:14.11-alpine
WORKDIR /app
ADD . /app
RUN npm i
RUN ls -la /app
RUN ls -la /app/test
RUN npm t
# No CMD as we don't want to start the server
# Docker compose (Automated tests) will execute the 'npm test' command.
